language: java
jdk:
  - openjdk7
  - oraclejdk8
script: "mvn --show-version --errors --batch-mode -Prun-its clean verify"
cache:
    directories:
    - $HOME/.m2
    - target
branches:
    except:
        - gh-pages
notifications:
    email:
        - avnerht@gmail.com
